name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:  |
        echo "${{ secrets.DockerHub }}" | docker login -u "manascomp" --password-stdin
        docker image build -t manascomp/time_tracking:latest . --tag time_tracking:$(date +%s)
        docker push manascomp/time_tracking:latest
        
